### ISSUE TITLE
User can add a new artist to their roster

### ISSUE THREAD

**Issue by nsturz** [nsturz/TM-Pro#1]
## ⚙️ Feature

User will be able to add a new artist to their roster after filling out a from. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

-  After filling out the form, user is taken to a blank dashboard page where they can begin adding tour dates. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="659" alt="Screen Shot 2022-09-19 at 12 37 02 PM" src="https://user-images.githubusercontent.com/94485412/191101200-f6cd2908-7506-4fab-b559-ee9a2c0c0332.png">

<img width="742" alt="Screen Shot 2022-09-16 at 5 23 02 PM" src="https://user-images.githubusercontent.com/94485412/190833282-71a299c7-7ac5-4b58-b817-a6ac6b48ee5a.png">

![Screen Shot 2022-09-19 at 3 19 18 PM](https://user-images.githubusercontent.com/94485412/191129648-62bbda86-41eb-49ac-b889-70c2b3295c9b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to...
  - [x] create the table "**artists**" with columns "artistId" and "name" 
  - [x] create the table "**venues**" with columns "venueId", "name", 'addressId" and "phone"
  - [x] create table "**notes**" with columns "createdAt", "details" and "showId"  
  - [x] create the table "**schedules**" with the columns "startTime", "endTime", "details" and "showId"
  - [x] create the table "**contacts**" with the columns 'details", "name", "phone", and "showId"
  - [x] create the table "**addresses**" with columns "addressId", "line1", "city", "state" and "country" 
  - [x] create the table "**shows**"  with the columns "showId", "venueId", "artistId" and "date"
 - [x] Update `data.sql` to ...
   - [x]  insert an "artistId" and "name" into "artists"
   - [x] insert a "venueId", "name", 'addressId" and "phone" into "venues"
   - [x] insert "details" and "showId"  into "notes"
   - [x] insert "startTime", "endTime", "details" and "showId" into "schedules" 
   - [x] insert "details", "name", "phone", and "showId" into "contacts"
   - [x] insert "addressId", "line1", "city", "state" and "country" into "addresses" 
   - [x] insert "showId", "venueId", "artistId" and "date" into "shows'

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
  - [x] call the `post` method of the `app` object to the path `/api/artists` and inside of it's callback function...
  - [x] if the request parameters were entered incorrectly (due to a number of reasons), respond with a `status code` of `400` with a JSON error response object detailing the problem
  - [x] if the request was good, write SQL code that inserts the artist name into the "artists" table
  - [x] query the database,
  - [x] THEN: respond with a status code of `201` and a json response of the `result.rows`
  - [x] CATCH any errors with `.catch`, log the error to the console `console.error(err)` , and respond with a status code of `500` and a JSON error object stating `an un expected error occured`.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

  - [x] Create `index.jsx` and import `React` and  `ReactDOM`.
    - [x] create `container` and  `root` elements and render them to the DOM. 
  - [x] Create a `form.jsx` (put `export default` before defining) and inside of it...
    - [x] import `React`
    - [x] Define a new `class` component called `Form` that `extends React.Component` and inside its code block...
    - [x] Define a `constructor` function and within its code block...
    - [x] call `super(props)`
    - [x] Bind `this` to the `handleChange` and `handleSubmit` functions
  - [x] Define a `render` function that renders a form to appear on the page like the wireframe. 
    - [x] Make the "Artist Name" input field `required`
  - [x] Define a `handleChange` function that takes a parameter of `event` and in its code block...
    - [x] Use `this.setState` to change the value of the `name` property in the object to `event.target.value`
   - [x] Define a `handleSubmit` function that takes a parameter of `event` and inside its code block...
   - [x] call the `preventDefault` method of the `event` object.
   - [x] create a new object that has a property of `name` and a value of `this.state.name` and save it to the constant `newArtist`
   - [x] call the `onSubmit` method of the `props` property of the `this` object and pass in the constant created above
   - [x] use `this.setState` to change the value of the `name` property back to `' '`
   - [x] Ensure that the `onSubmit` property of the `<form>` element calls `this.handleSubmit`
- [x] Create an `app.jsx` and import `React`, and `Form` component from `form.jsx`
  - [x] Create a `class` called App that `extends React.Component` (use `export default` before defining) and in its code block...
  - [x] Define a `constructor` function and in its code block...
  - [x] Call `super(props)`
  - [x] Set `this.state` to equal an object that has a property of `artists` with a value of an empty array `[ ]
  - [x] Define a function called `addName` that takes a parameter of the constant `newArtist` that was defined in `Form` and in its code block ...
  - [x] Use `FETCH` to send a `POST` request to `/api/artists`
  - [x] Ensure the method is `POST`, the header `content-type` is `application/json`, and the `body` is `JSON.stringify(newArtist)`
  - [x] THEN send a `response.json()`
  - [x] THEN use `this.setState` to change the value of `name` to `this.state.artists.concat(artists)`
  - [x] CATCH any errors and log them to the console with `console.error`
  - [x] Test `POST` requests with HTTPie
- [x] Bind `this` to `addName` in the constructor function
- [x] Define a function called `componentDidMount` and inside its code block...
  - [x] Call the `addListenerEvent` method of the `window` object and in its callback function...
  - [x] Use `this.setState` to change the value of `route` to `parseRoute(window.location.hash)`
- [x] Define a function named `renderPage`  that takes no parameters and inside it's code block...
  - [x] Destructure `route` from `this.state`
  - [x] If the `route.path` is strictly equal to an empty string, return `<Dashboard />`
  - [x] If the `route.path` is strictly equal to `form`, return `<Form />`
  - [x] Otherwise, return `<NotFound />` by default
 - [x] Create a `dashboard.jsx` 
 - [x] Define a class component called `Dashboard` and inside of its code block ...
   - [x] call a `render` function that returns a page that looks like the empty dashboard view in the wireframe. 
- [x] Create a `navbar.jsx` page
  - [x] Define a class component called `NavBar` and inside its code block...
  - [x] Define a `render` function that returns a navbar like the one in the wireframe 
  - [x] Ensure the `navbar` has "dropdown" capabilities.   
- [x] Create a `footer.jsx` page and style it to look like the wireframe. 
- [x] Back in `app.jsx`, create a `render` function and within its code block: 
  - [x] create a `container` div element that will contain all the proceeding elements
  - [x] insert the `img` element as the background and blur it to match the wireframe
  - [x] add `Navbar` component 
  - [x] below `Navbar`, call `{ this.renderPage }` so that the appropriate page is always displayed
  - [x] below that, add the `Footer` component.
 

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure all components use `export default` where necessary
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
