### ISSUE TITLE
User can edit a tour date. 

### ISSUE THREAD

**Issue by nsturz** [nsturz/TM-Pro#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to edit the details of a tour date if they wish. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- User clicks "edit date" on the clipboard page. 
- Empty form appears with greyed out values. 
- User selects which date they want to edit from a dropdown menu.
- Input fields populate with the applicable information from the selected show.  
- User edits whichever field they wish. 
- After pressing "submit", the data is changed and reflected immediately. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="678" alt="Screen Shot 2022-11-11 at 11 38 14 AM" src="https://user-images.githubusercontent.com/94485412/201417205-3a5d39dc-922d-4fcd-80f0-ac102686357f.png">

![Screen Shot 2022-11-03 at 1 11 20 PM](https://user-images.githubusercontent.com/94485412/199824313-e9026fa3-8059-45bd-b4e4-9be03a30668e.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Create a new `GET` request to `'/api/shows'` that gets the following details from the database: `showId`, `venueId`, `artistId`, `date`, `venueName`,  `addressId`, `startTime`, `endTime`, `scheduleDetails`, `details` from notes, `email`, `name`, `phone` from contacts, and `line1`, `state`, `city` and `country`
- [ ] Create a new `PATCH` request to `/api/shows/:showId` that updates `date`, `venueName`, `startTime`, `endTime`, `scheduleDetails`, `details`, `email`, `name`, `phone`, `line1`, `state`, `city`, `and `country` to the appropriate values
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client with an object that contains the values above

### ⚡ Client Tasks

- [x] In `app.jsx`, add `<EditTourDate / >` to the `renderPage` method and pass it a prop called `tourDates` with a value of `this.state.tourDates`
- [x] Create a component called `edit-tour-date` and in its code block...
- [x] Define a constructor function, and define the state for `show` and give it the value of an empty string. 
- [x] Define a method called `selectDate` that takes a parameter of `event`, and in its code block...
- [x] Iterate through `this.props.tourDates` and IF the `event.target.id` is strictly equal to `this.props.tourDates[i].showId`...
- [x] Make a Fetch `GET` request to `/api/shows/${this.props.tourDates[i].showId}`
- [x] Ensure the response gets parsed (`response => response.json()`)
- [x] THEN set the state of show in state according to the response
- [x] Define a `render` method and return a page identical to the `new-tour-date` form. 
- [ ] Add a title to the page that says "EDIT DATE"
- [x] Assign each `<input/>` a `value` attribute with a value of its corresponding value from state.
- [x] Define a `handleChange` method for each input field like in `new-tour-date.jsx`. Each one should take a parameter of `event ` and in their code block, set the state to the `event.target.value`
- [ ] Define a `handleSubmit` method that takes a parameter of `event` and is identical to the one in `new-tour-date.jsx`, but the object should be called `editedTourDate` instead of `newTourDate`
- [ ] In `app.jsx` create a `editDate` method that sends a fetch `PATCH` request to the server with `editedTourDate` as its payload and...
- [ ] THEN create a shallow copy of the `tourdates` array from state, iterate through it, and replace the applicable tour date with the edited tour date. 

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
