### ISSUE TITLE
User can view route overview

### ISSUE THREAD

**Issue by nsturz** [nsturz/TM-Pro#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view a map powered by the Google Maps API that shows them the route for their next drive, and how many miles they will be traveling. The map updates once a show's date has passed. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- User clicks the "map" icon on the bottom navbar. 
- User is automatically taken to the "Route Overview" page, where they can view the overview of their map.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-02 at 5 36 47 PM](https://user-images.githubusercontent.com/94485412/205416299-3f3c5dc7-d9e1-4e2e-8797-3a10904c3337.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature

### ⚡ Client Tasks

- [x] Create a component called `route-overview.jsx`
- [x] Give  `<RouteOverView />`  a constructor method, initializing state for the following variables: `origin` and `destination` to empty strings `''`, `travelMode` : `‘DRIVING’`, `response` :`null`
- [x] Inside of `app.jsx`, update `renderPage( ) ` to conditionally switch to `<RouteOverView />` based on hash routing. 
- [x] Give `<RouteOverview />` a prop of `tourDates={this.state.tourDates}`
- [x] Change anchor tag for the "calendar" anchor tag in `footer.jsx` to have an `href` value of `#map`
- [x] For each defined method, be sure to bind it to `this` in the constructor method. 
- [x] Finish section titled "Google Maps Implementation" before moving forward with this section
- [x] Inside the render method, give the appropriate HTML element a value of `{ this.state.showsLeft }` 
- [x] Inside the render method, give the appropriate HTML element a value of `{ this.state.distance }`

### Google Maps Implementation
- [x] Follow steps at https://react-google-maps-api-docs.netlify.app/ for installing a Google Map onto the page (stop at the "components" section")
- [x] Once the map is loaded successfully onto the page, style the rest of the page according to the wireframe. 
- [x] Import `{ useJsApiLoader, GoogleMap, Marker, DirectionsRenderer}`  from `@react-google-maps-api`
- [x] Wrap `<GoogleMap />` in the `<LoadScript />` tag, and give `<LoadScript />` a prop of `googleMapsApiKey` with a value of `process.env.YOUR_KEY`
- [x] Give `<GoogleMap />`  a prop of `center` (use a relevant lat / long), `zoom`, and `mapContainerStyle` with a width and height that resemble the wireframe. 
- [x] Define a `componentDidMount( )` method and in its code block... 
- [x] Grab `dateCity` and `dateState` from indexes 0 and 1 and set the state of `origin` and `destination` accordingly. 
- [x] Define a method called `directionsCallback( )` that takes one parameter `response` and in its code block…
- [x] If `response` is not strictly equal to `null`, check IF `response.status` is strictly equal to `‘OK’` and if it is, **set the state** of `response` to `response`.
For anything ELSE, console.log the response.
- [x] Insert `<DirectionsService />` as a child element to `<GoogleMap />`, and ensure it has props `options` and `callback`, but ensure that it only renders if `this.state.origin` and `this.state.destination` are **strictly unequal** to empty strings `''`.
- [x] Give the `options` prop a value of an `object` which contains the properties `origin`, `destination`, and `travelMode`, with values from **state**, and give the `callback` prop a value of `this.directionsCallback`
- [x] Insert `<DirectionsRenderer />` as a sibling to `<DirectionsServerice />` and ensure if has a prop of `options` that has a value of an `object`, which has a property of `directions`, which has a value of `this.state.response`.
- [x] Ensure that `<DirectionsRenderer/> `only renders if `this.state.response` is **strictly unequal** to `null`.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
