### ISSUE TITLE
Design Update 1.0 - Redesign of application's UI

### ISSUE THREAD

**Issue by nsturz** [nsturz/TM-Pro#24]
## ⚙️ Feature

> ##### Which feature is affected by this update?

 - All functionality will remain the same, but the app will have a new look, with a simplified color scheme and a cleaner layout. 

## 📐 Plan

> ##### Summary of the technical approach to be taken.

- Updates to the `dashboard`, `tourDates`, `routeOverview`, `editTourdate`, and `newTourDate` components will be made via Bootstrap classes and CSS.
- Navbar at the top of the app will now have all of the navigation controls, removing the need for the navbar at the bottom, as well as removing the need for the "clipboard" page. 

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

### Desktop Dashboard view
<img width="741" alt="Screen Shot 2023-01-16 at 1 45 41 PM" src="https://user-images.githubusercontent.com/94485412/212770302-2a65ce7f-f254-4897-9cc9-f330abeac47f.png">

### Desktop Tour Dates view
<img width="742" alt="Screen Shot 2023-01-16 at 1 45 52 PM" src="https://user-images.githubusercontent.com/94485412/212770322-cd909c80-cb00-46bd-90b5-52d032ed0820.png">

### Desktop Route Overview
<img width="740" alt="Screen Shot 2023-01-16 at 1 46 04 PM" src="https://user-images.githubusercontent.com/94485412/212770336-72a0579a-c5f3-4b36-b467-b187396135e1.png">

### Desktop New Date / Edit Date view
<img width="739" alt="Screen Shot 2023-01-16 at 1 46 13 PM" src="https://user-images.githubusercontent.com/94485412/212770356-2cefca31-fa16-44f8-ba74-45d91abd2052.png">

### Mobile Layouts
<img width="269" alt="Screen Shot 2023-01-16 at 1 43 16 PM" src="https://user-images.githubusercontent.com/94485412/212770381-e8c7afde-3cb5-4e5a-b007-8928bf1715e1.png"> <img width="268" alt="Screen Shot 2023-01-16 at 1 44 44 PM" src="https://user-images.githubusercontent.com/94485412/212770400-47ecd2e0-8a9b-43cd-8f77-7e9e8385d1f4.png"> 
<img width="268" alt="Screen Shot 2023-01-16 at 1 45 01 PM" src="https://user-images.githubusercontent.com/94485412/212770422-7e20ba55-9cbd-4c2f-80ea-3a01a0c37223.png"> <img width="270" alt="Screen Shot 2023-01-16 at 1 45 13 PM" src="https://user-images.githubusercontent.com/94485412/212770441-bfd27c60-ee6f-4bea-afd1-0c3934696c06.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In `index.html`, put two `<link/>` elements between the head tags; one for the Google font `Lato Bold 700` and the other for the Google Font `Poppins Semi bold 600`
- [x] Change the values of the `font-family` attributes in the rule sets for `h6`, `h3` and `span` tags to the `Poppins` font. 
- [x] Change the values of the`font-family` attributes in the rule sets for `p`, `pre` and `li`, and `a` tags to the `Lato` font. 
- [x] Create a React component called `navbar.jsx` and in it, render a JSX element that matches the wireframes above.
- [x] Ensure that the **More** navigation link presents a dropdown, with links to `<NewTourDate />` and `<EditTourDate />`
- [x] Insert `<NavBar />` into the `render` method in `app.jsx` above `{this.renderPage( )}`
- [x] For `dashboard.jsx`...
- [x] Remove the background image, and replace it with the solid color `#121212`
- [x] Change the color of the boxes to `#3D3D3C`, round out the corners, and remove the borders.
- [x] Take the `h6` elements for _Venue_, _Notes_, _Schedule_, _Dates_, and _Contacts_ out of the boxes, and ensure their placement via the wireframe.
- [x] Change the color of each icon to `#CD3C3A`
- [x] Ensure clickable elements change their color to `#CD3C3A` when hovered. 
- [x] Ensure element placement matches wireframes on both desktop and mobile. 
- [x] For `tourDates.jsx`...
- [x] Remove the border, change background color of the body, and ensure  _**every other**_ `<li/>` element has a background color of `#3D3D3C`
- [x] Change the _**delete modal wrapper**_ background to `#FFFFFF`
- [x] Change the **_confirm_** button background to `#CD3C3A`
- [x] Change the _**cancel**_ button background color to `#000000`
- [x] Ensure element placement matches wireframe for both desktop and mobile. 
- [x] For `routeOverview.jsx`...
- [x] Remove borders from both boxes, change their colors, and change the background color of the body. 
- [x] Ensure element placement matches wireframe for both desktop and mobile. 
- [x] For `edit-tour-date.jsx` and `new-tour-date.jsx`, remove the border around the forms, and change the background color of the body. 
- [x] Ensure element placement matches wireframe for both desktop and mobile. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
