### ISSUE TITLE
User can view tour details on their dashboard

### ISSUE THREAD

**Issue by nsturz** [nsturz/TM-Pro#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Dashboard will display all information relevant to the specific tour date details from the database. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After adding tour dates and artist info, the main dashboard page will display crucial tour info pertinent to that day. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-24 at 4 52 47 PM](https://user-images.githubusercontent.com/94485412/192122688-be52ec20-9e17-4175-b4fb-1c936136c482.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Make `GET` requests to `/api/venues/:venueId`  and select `name`, `addressId`, and `phone` 
- [x] Make `GET` requests to `/api/notes/:notesId` and select `details`
- [x] Make `GET` requests to `api/schedules` and select `startTime`, `endTime`, and `details` where `showId` is `1`
- [x] Make `GET` requests to `api/contacts/:contactId` and select `email`, `name`, and `phone`
- [x] Make `GET` requests to `api/shows/:showId` and select `venueId`, and `date`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Inside the `Dashboard` component's code block...
- [x]  Create a `constructor` function that takes a parameter of `props` and inside of its code block...
- [x] Call `super(props)`
- [x] Set the state of the property `show` to `null`
- [x] Below `constructor`, create a new `componentDidMount` function  that takes no parameters and inside its code block...
- [x] Create a `fetch` request for `/api/venues/:venueId`
- [x] Create a `fetch` request for `/api/notes/:notesId`
- [x] Create a `fetch` request for `/api/schedules`
- [x] Create a `fetch` requestsfor `/api/contacts/:contactId `
- [x] Create a `fetch` request for `/api/shows/:showId`
- [x] Inside of the  `render( )` function's code block, destructure  all appropriate values from their respective state. 
- [x] Inside if the `return ( )` function's code block...
- [x] Build the page to look like the wireframe, and plug in the destructured values where need be. 
- [x] For `SCHEDULES`, iterate through the array `this.state.schedules` and for each index, return an `<li>` 
- [x] For 'DATES`, iterate through the array `this.state.dates` and for each index, return an `<li>`

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
