### ISSUE TITLE
UI Redesign 2.0 - Add Show

### ISSUE THREAD

**Issue by nsturz** [nsturz/TM-Pro#30]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add a new show like in the original app, but it will all be on the same page using modals. 

## 📐 Functionality

- User clicks on the "plus sign" button. 
- A modal appears, allowing user to enter information for a new show. 
- When user clicks "save", the show is saved to the database and can be searched for in the "search" bar at the top of the page. 

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="679" alt="Screen Shot 2023-05-19 at 3 57 19 PM" src="https://github.com/nsturz/TM-Pro/assets/94485412/2cd218a2-2bf2-4fb5-954a-e5864ae1e1d0">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update the `<NewTourDate />` component to be styled like the wireframe. 
- [x] Add the three buttons (add, edit, delete) to the `<Dashboard />` page. 
- [x] Ensure all functionality remains intact, and that after filling out the modal, the client side successfully submits the information to the database. 
- [x] Once functionality is complete, ensure that the modal appears when the "plus sign" button is clicked. 

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
