### ISSUE TITLE
UI Redesign 2.0 Edit Date

### ISSUE THREAD

**Issue by nsturz** [nsturz/TM-Pro#32]
## ⚙️ Feature

> ##### Which feature is affected by this update?

## 📐 Plan

> ##### Summary of the technical approach to be taken.

- User presses the "edit" button. 
-  A modal appears, pre-filled with information about the current date that is displayed. 
- User edits the fields they wish to change. 
- After pressing "update", the information is changed in the database, and reflected on the page. 

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

<img width="763" alt="Screen Shot 2023-05-22 at 6 12 30 PM" src="https://github.com/nsturz/TM-Pro/assets/94485412/d168329c-de21-4bd6-bf9d-81992ac1c7c4">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Update the `<EditTourDate />` component to look like the wireframe
- [ ] Ensure all `handleChange()` functions work, and properly change the values in state. 
- [ ] Ensure that on submit, the data is updated in the database. 
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
