### ISSUE TITLE
User can create a new tour date

### ISSUE THREAD

**Issue by nsturz** [nsturz/TM-Pro#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

After filling out a form, a new tour date will appear on the dashboard and "tour dates" page 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- User clicks on the "clipboard" button. 
- User selects "new tour date"
- User fills out the form. 
- New date becomes visible on the 'calendar" page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-10-03 at 4 45 14 PM](https://user-images.githubusercontent.com/94485412/193705219-240cec02-a99f-401a-bfa7-bcea2e033699.png)

<img width="735" alt="Screen Shot 2022-09-30 at 3 14 58 PM" src="https://user-images.githubusercontent.com/94485412/193363649-c45775ca-cb75-4cb9-b88f-150f66c5dcef.png">

![Screen Shot 2022-10-03 at 4 15 47 PM](https://user-images.githubusercontent.com/94485412/193705180-b6462de8-003c-4843-a952-698d2d709d58.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Make `POST` requests to:
- [x] `/api/addresses`
- [x] `/api/contacts`
- [x] `/api/venues`
- [x] `/api/notes`
- [x] `/api/schedules`
- [x] `/api/shows`
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Inside `app.jsx`, define a new function named `addTourDate`, and in its code block...
- [x] Make `POST` fetch requests to the server.
- [x] Create a new page called `clipboard` that allows user to select between "New Artist", 'New Tour",  "New Tour Date", or 'Edit Tour Date"
- [x] Update `clipboard` to look like the wireframe for both desktop and mobile. 
- [x] Create a new page called `TourDates` 
- [x] Style it to look like the wireframe, on both desktop and mobile. 
- [x] Create a new Component called `NewTourDate` and in its `render` function... 
- [x] `return` a page that looks like the wireframe, on both desktop and mobile. 
- [x] Ensure the "Date" section is a calendar type input
- [x] Ensure "Location", "Notes", and "Contacts" sections are type "text" input. 
- [x] Ensure "Schedule" section is type  a "time" input type, and "details" is a text input. 
- [x] Add 10 options for the above sequence, but ensure 9 are hidden, and 1 is showing. 
- [x] Add a "+" icon, wrapped in a `button` element,  below the schedule inputs and style it to look nice on mobile / desktop. 
- [x] Above `render` method, create a new method called `addScheduleEvent` and in its code block...
- [x] Create functionality that reveals a new `time` and `details` section every time the user clicks. 
- [x] Define a `constructor` function inside of `NewTourDate`
- [x] Bind `this` to `addScheduleEvent` in the constructor function
- [x] Inside the `render` method, ensure the `+` icon has a property of `onClick` with a value of `this.addScheduleEvent`
- [x] Inside `NewTourDate`'s constructor function, set the initial state for the following variables: 
- [x] line1 - `''`
- [x] city - `''`
- [x] state - `''`
- [x] country - `''`
- [x] email - `''`
- [x] contactName - `null`
- [x] contactPhone - `''`
- [x] details - `''`
- [x] startTime - `null`
- [x] endTime - `null`
- [x] scheduleDetails - `''`
- [x] date - `null`
- [x] venueName - `''`
- [x] venuePhone - `''`
- [x] Bind `this` to `handleChange` and `handleSubmit`
- [x] Inside of `NewTourDate`, define a `handleChange` function that takes one parameter `event` for each input, and within its code block, set the state of the according value to `event.target.value`
- [x] Inside of `NewTourDate`, define a `handleSubmit` function that takes one parameter `event` and...
- [x] Prevent default actions from occurring
- [x] Create a new object, with properties that match each instance of state, with values of each corresponding `this.state.___` and save it to a variable called `newTourDate` 
- [x] Call `this.props.onSubmit` and pass in `newTourDate` as an argument
- [x] Call the `setState` method of the `this` object and  assign each property back to a value of an empty string or null, like it was in the original constructor function. 
- [x] Query the DOM for the `new-tour-date form` by ID and reset it. 
- [x] Ensure the`<form/>` element  inside of `NewTourDate`'s render function has an `onSubmit` property with a value of `this.handleSubmit` 
- [x] Ensure each `<input/>` element has an associated `onChange` prop that has a corresponding value of `this.handle____`
- [x] Inside `app.jsx`, modify the `renderPage` function to add the `clipboard` page, `NewTourDate` component, and the `TourDates` component. 
- [x] Make sure `addTourDate` is a function that fires off all of the fetch `POST`  request methods. 
- [x] Inside the above `render` function, give the `<NewTourDate />` component a property of `onSubmit` with a value of`{ this.addTourDate }`
### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
