### ISSUE TITLE
 User can delete tour date

### ISSUE THREAD

**Issue by nsturz** [nsturz/TM-Pro#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to delete any tour date if they wish. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- User clicks on the "trash can" icon on any date displayed on the "calendar" page. 
- A modal appears, asking if they user would like to confirm their decision. 
- If "cancel" is clicked, modal disappears. 
- If "confirm" is clicked, the tour date is deleted. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="678" alt="Screen Shot 2022-10-27 at 9 18 40 AM" src="https://user-images.githubusercontent.com/94485412/198344861-cd9052d7-a7d2-4732-bd24-f28a0311c6f6.png">

<img width="677" alt="Screen Shot 2022-10-27 at 9 19 04 AM" src="https://user-images.githubusercontent.com/94485412/198344896-912ade9d-a5ff-4354-92bb-bfaa9e625502.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Create a DELETE request to `/api/delete-date` that removes all applicable rows from `contacts`, `shows`, `notes`, and `schedules` that share the same `showId`. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Inside of `tourdates.jsx`...
- [x] Modify the `render` method to display the actual data from the database using `.map` on `this.props.tourDates`
- [x] define a `constructor` method and call `super(props)` in its code block. 
- [x] Set the state of `showId` to `null`
- [x] Give each `<li />` element an `id` attribute and set its value to `event.showId` 
- [x] Build the modal, and once styled like the wireframe, add `d-none` to its className 
- [x] Define a `handleClick` method and in its code block...
- [x] conditionally hide or unhide the modal based on whichever applicable buttons the user clicks (i.e. trash can or cancel)
- [x] Ensure that the "confirm" button on the modal is of `type="submit"` in the HTML markup. 
- [x] define a `handleSubmit` method that takes a parameter of `event` and in its code block...
- [x] set the state of `showId` to `event.target.showId` (you may need to call `Number( )` on this)
- [x] Inside of `app.jsx`, pass `<TourDates />` a prop of `tourDates={ this.state.tourDates }` and a prop of `onSubmit={ this.deleteTourDate }`
- [x] Define a method called `deleteTourDate` that takes a parameter of `(selectedDate)` and in its code block...
- [x] Create a `fetch` request to `/api/delete-date`
- [x] After `.then(response => response.json(selectedDate))`...
- [x] Use the spread operator to create a copy of the `tourDates` array i.e. `[ ...this.state.tourDates ]`
- [x] Iterate through the objects inside the copied array, and if the `showID` of the index `(event.showId)` matches the `event.target.id`, delete it from the array (you may need to call `Number( )` on the `event.target.id`)
- [x] Set the state of `tourDates` and replace it with the new copy of the array

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
